enchant-success-rate: 70  # 인챈트 성공 확률 (0~100 사이의 값)

explosion-radius: 2.0

lightning-range: 5.0

ice-arrow-radius: 5
ice-arrow-freeze-chance: 0.3  # 화살이 맞았을 때 블록이 얼음으로 변할 확률
ice-entity-freeze-chance: 0.2 # 엔티티 주변의 블록이 얼음으로 변할 확률

fire-arrow-radius: 8  # 화염 화살의 반경을 설정
fire-arrow-duration: 5  # 엔티티가 불에 타는 시간 (초 단위)
fire-arrow-transform-chance: 0.5  # 마그마 블록으로 변환될 확률 (0.0 ~ 1.0)

explosion-damage-reduction: 0.5

experience: 5345

player-walk-speed: 1.7


# The name of the special Elytra
elytra-name: "&6Special Elytra"

elytra-remove-y: 150  # Elytra가 제거될 Y좌표

# Whether to allow moving the Elytra in the inventory (true/false)
allow-move: false

# Whether to allow dropping the Elytra (true/false)
allow-drop: false

# 처음 텔레포트 Y좌표 설정
teleport-y-coordinate: 600

slow-falling-duration: 10  # 날개 제거후 느린 낙하 지속 시간 (초 단위)

chestProbability:
  dungeon: 0.01   # 백 블럭당 하나
  building: 0.001 # 천 블럭당 하나
  busstop: 0.1    # 10 블럭당 하나

chest_contents:
  categories:
    guns: 0.2   # guns 카테고리의 총 확률
    arrows: 0.5 # arrows 카테고리의 총 확률
    armors: 0.3 # armors 카테고리의 총 확률

  guns: # 총기류 카테고리
    gun1:
      probability: 0.4  # 40% 확률
      item:
        ==: org.bukkit.inventory.ItemStack
        type: IRON_SWORD
        amount: 1
    gun2:
      probability: 0.6  # 60% 확률
      item:
        ==: org.bukkit.inventory.ItemStack
        type: CROSSBOW
        amount: 1

  arrows: # 화살 카테고리
    arrow1:
      probability: 0.7  # 70% 확률
      item:
        ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 16
    arrow2:
      probability: 0.3  # 30% 확률
      item:
        ==: org.bukkit.inventory.ItemStack
        type: TIPPED_ARROW
        amount: 8

  armors: # 아머 카테고리
    armor1:
      probability: 0.5  # 50% 확률
      item:
        ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_CHESTPLATE
        amount: 1
    armor2:
      probability: 0.5  # 50% 확률
      item:
        ==: org.bukkit.inventory.ItemStack
        type: IRON_HELMET
        amount: 1

  dummydata:
    # 명령어로 등록된 더미 아이템들
    item1:
      item: # 직렬화된 아이템 데이터
        ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_SWORD
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 5
    item2:
      item: # 직렬화된 아이템 데이터
        ==: org.bukkit.inventory.ItemStack
        type: BOW
        amount: 1
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC


phase1:
  breaktime: 220
  add: -100
  shrinktime: 120
  damage: 0.1

phase2:
  breaktime: 180
  add: -100
  shrinktime: 100
  damage: 0.15

phase3:
  breaktime: 120
  add: -100
  shrinktime: 80
  damage: 0.3

phase4:
  breaktime: 90
  add: -100
  shrinktime: 50
  damage: 0.5

phase5:
  breaktime: 60
  add: -90
  shrinktime: 60
  damage: 1


