explosion-radius: 2.0

lightning-range: 5.0

ice-arrow-radius: 5
ice-arrow-freeze-chance: 0.3  # 화살이 맞았을 때 블록이 얼음으로 변할 확률
ice-entity-freeze-chance: 0.2 # 엔티티 주변의 블록이 얼음으로 변할 확률

fire-arrow-radius: 8  # 화염 화살의 반경을 설정
fire-arrow-duration: 5  # 엔티티가 불에 타는 시간 (초 단위)
fire-arrow-transform-chance: 0.5  # 마그마 블록으로 변환될 확률 (0.0 ~ 1.0)

experience: 5345


# The name of the special Elytra
elytra-name: "&6Special Elytra"

elytra-remove-y: 150  # Elytra가 제거될 Y좌표

# Whether to allow moving the Elytra in the inventory (true/false)
allow-move: false

# Whether to allow dropping the Elytra (true/false)
allow-drop: false

# 처음 텔레포트 Y좌표 설정
teleport-y-coordinate: 600

slow-falling-duration: 10  # 날개 제거후 느린 낙하 지속 시간 (초 단위)



phase1:
  breaktime: 220
  add: -100
  shrinktime: 120
  damage: 0.1

phase2:
  breaktime: 180
  add: -100
  shrinktime: 100
  damage: 0.15

phase3:
  breaktime: 120
  add: -100
  shrinktime: 80
  damage: 0.3

phase4:
  breaktime: 90
  add: -100
  shrinktime: 50
  damage: 0.5

phase5:
  breaktime: 60
  add: -90
  shrinktime: 60
  damage: 1


