name: MineGround
version: '${project.version}'
main: org.battle.mineground.MineGround
api-version: '1.20'
commands:
  mg:
    description: Main command for MineGround plugin
    usage: /mg <start|stop|reload|load|check>
  switcharrow:
    description: Switches the currently held arrow to the next one in the inventory.
    usage: /switcharrow
  giveelytra:
    description: Gives the player a special Elytra.
    usage: /giveelytra
    permission: mineground.giveelytra
    permission-message: You do not have permission to use this command.
  showpointer:
    description: "특정 좌표를 가리키는 포인터를 생성합니다."
    usage: "/showpointer <x> <y> <z>"


permissions:
  mineground.elytra:
    description: Allows the player to use the /elytra command.
    default: op  # 기본적으로 오퍼레이터만 명령어를 사용 가능하게 설정